CREATE TABLE "MCBBCM"."BCM_ORDER"(
	BCM_ORDER_ID					NUMBER(10),
	BCM_ORDER_REF 			VARCHAR2(2000), 
	BCM_ORDER_DATE 			DATE,
	BCM_ORDER_TOTAL_AMOUNT 	NUMBER(20),
	BCM_ORDER_DESCRIPTION 		VARCHAR2(2000),
    BCM_ORDER_STATUS 			VARCHAR2(2000),
	CONSTRAINT "ORDER_PK" PRIMARY KEY ("BCM_ORDER_ID"),
	CONSTRAINT "ORDER_UNIQUE_CONSTRAINT" UNIQUE("BCM_ORDER_REF")
	
);

CREATE TABLE "MCBBCM"."ORDER_LINE"(
	BCM_ORDER_LINE_ID		NUMBER(10),	
	BCM_ORDER_LINE_REF 		VARCHAR2(2000), 
	BCM_ORDER_LINE_AMOUNT 	VARCHAR2(2000), 
	BCM_ORDER_ID			NUMBER(10),
	CONSTRAINT "ORDER_LINE_PK" PRIMARY KEY ("BCM_ORDER_LINE_ID"),
	CONSTRAINT "ORDER_LINE_UNIQUE_CONSTRAINT" UNIQUE("BCM_ORDER_LINE_REF"),
	CONSTRAINT "ORDER_LINE_FK" FOREIGN KEY ("BCM_ORDER_ID")
	  REFERENCES "MCBBCM"."BCM_ORDER" ("BCM_ORDER_ID") ON DELETE CASCADE ENABLE	
);

CREATE TABLE "MCBBCM"."SUPPLIER"(
	BCM_SUPPLIER_ID			NUMBER(10),
	BCM_SUPPLIER_NAME 		VARCHAR2(2000), 
	BCM_SUPP_CONTACT_NAME 	VARCHAR2(2000), 
	BCM_SUPP_ADDRESS 		VARCHAR2(2000), 
	BCM_SUPP_CONTACT_NUMBER VARCHAR2(2000),
	BCM_SUPP_EMAIL 			VARCHAR2(2000),	
	CONSTRAINT "SUPPLIER_PK" PRIMARY KEY ("BCM_SUPPLIER_ID")
);

CREATE TABLE "MCBBCM"."SUPPLIER_ORDER"(
	BCM_SUPPLIER_ID			NUMBER(10),
	BCM_ORDER_ID			NUMBER(10),
	CONSTRAINT "SUPPLIER_ORDER_PK" PRIMARY KEY ("BCM_SUPPLIER_ID","BCM_ORDER_ID"),
	CONSTRAINT "SUPPLIER_ORDER_FK" FOREIGN KEY ("BCM_SUPPLIER_ID")
	  REFERENCES "MCBBCM"."SUPPLIER" ("BCM_SUPPLIER_ID"),
	 CONSTRAINT "SUPPLIER_ORDER_ID_FK" FOREIGN KEY ("BCM_ORDER_ID")
	  REFERENCES "MCBBCM"."BCM_ORDER" ("BCM_ORDER_ID")
);

CREATE TABLE "MCBBCM"."INVOICE"(
	BCM_INVOICE_ID				NUMBER(10),
	BCM_INVOICE_REFERENCE 		VARCHAR2(2000), 
	BCM_INVOICE_DATE 			DATE, 
	BCM_INVOICE_DESCRIPTION 	VARCHAR2(2000),
	CONSTRAINT "INVOICE_PK" PRIMARY KEY ("BCM_INVOICE_ID")
);

CREATE TABLE "MCBBCM"."ORDER_INVOICE"(
	BCM_ORDER_LINE_ID		NUMBER(10),
	BCM_INVOICE_ID				NUMBER(10), 
	BCM_INVOICE_AMOUNT 			VARCHAR2(2000), 
	BCM_INVOICE_STATUS 			VARCHAR2(2000),
	BCM_INVOICE_HOLD_REASON 	VARCHAR2(2000),
	CONSTRAINT "ORDER_INVOICE_PK" PRIMARY KEY ("BCM_ORDER_LINE_ID","BCM_INVOICE_ID"),
	CONSTRAINT "ORDER_INVOICE_LINE_FK" FOREIGN KEY ("BCM_ORDER_LINE_ID")
	  REFERENCES "MCBBCM"."ORDER_LINE" ("BCM_ORDER_LINE_ID"),
	 CONSTRAINT "ORDER_INVOICE_FK" FOREIGN KEY ("BCM_INVOICE_ID")
	  REFERENCES "MCBBCM"."INVOICE" ("BCM_INVOICE_ID")
);

CREATE SEQUENCE  "MCBBCM"."SQ_ORDER_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;
CREATE SEQUENCE  "MCBBCM"."SQ_ORDER_LINE_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;
CREATE SEQUENCE  "MCBBCM"."SQ_SUPPLIER_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;
CREATE SEQUENCE  "MCBBCM"."SQ_ADDRESS_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;
CREATE SEQUENCE  "MCBBCM"."SQ_INVOICE_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;
