create or replace 
PACKAGE BCMORDER_PKG IS

PROCEDURE "MERGE_ORDER_PRC" (p_order_ref IN VARCHAR2 );
PROCEDURE "MERGE_ORDER_LINE_PRC" (p_order_ref IN VARCHAR2 );
PROCEDURE "MERGE_SUPPLIER_PRC" (p_order_ref IN VARCHAR2 );
PROCEDURE "MERGE_INVOICE_PRC" (p_order_ref IN VARCHAR2 );
PROCEDURE "MERGE_ORDER_INVOICE_PRC" (p_order_ref IN VARCHAR2 );

END BCMORDER_PKG;